export const ACTOR_STATE = {
  IDLE_RIGHT: 'IDLE_RIGHT',
  IDLE_DOWN: 'IDLE_DOWN',
  IDLE_LEFT: 'IDLE_LEFT',
  IDLE_UP: 'IDLE_UP',
  WALKING_RIGHT: 'WALKING_RIGHT',
  WALKING_DOWN: 'WALKING_DOWN',
  WALKING_LEFT: 'WALKING_LEFT',
  WALKING_UP: 'WALKING_UP',
};
