export enum ACTOR_STATE {
  IDLE,
  WALKING,
  DESTROYED,
  INVINCIBLE,
}

export enum ACTOR_DIRECTION {
  UP,
  DOWN,
  LEFT,
  RIGHT,
}

export const ACTOR_INVERTED_DIRECTION = {
  [ACTOR_DIRECTION.UP]: ACTOR_DIRECTION.DOWN,
  [ACTOR_DIRECTION.DOWN]: ACTOR_DIRECTION.UP,
  [ACTOR_DIRECTION.LEFT]: ACTOR_DIRECTION.RIGHT,
  [ACTOR_DIRECTION.RIGHT]: ACTOR_DIRECTION.LEFT,
};
